[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Force static site deployment
[context.production]
  publish = "out"
  command = "npm run build"

[context.deploy-preview]
  publish = "out"
  command = "npm run build"