[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Force static site deployment
[context.production]
  publish = "out"
  command = "npm run build"

[context.deploy-preview]
  publish = "out"
  command = "npm run build"

# 리다이렉트 설정 (네이버 블로그 카드 방지용)
[[redirects]]
  from = "/blog"
  to = "/"
  status = 301

# 홈 경로 제거: 루트로 접근 시 소개 페이지로 이동
[[redirects]]
  from = "/"
  to = "/about"
  status = 301

# 보안 잠금: 모든 경로를 404로 처리 (최후 우선순위)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/naver"
  to = "/"
  status = 301

[[redirects]]
  from = "/banner"
  to = "/"
  status = 301